package in.ac.caluniv.cse.ubrca.artifact;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Writes publication-quality Python/matplotlib plotting scripts alongside each
 * experiment output. The scripts consume the generated raw CSV files and create
 * clean vector and high-resolution raster figures for manuscript typesetting.
 */
public final class PythonPlotScriptWriter {
    private PythonPlotScriptWriter() {}

    public static void write(Path output) throws IOException {
        Path scripts = output.resolve("scripts");
        Files.createDirectories(scripts);
        Files.writeString(scripts.resolve("plot_publication_figures.py"),
                pythonScript(), StandardCharsets.UTF_8);
        Files.writeString(scripts.resolve("README.md"), readme(),
                StandardCharsets.UTF_8);
        Files.writeString(scripts.resolve("requirements.txt"),
                "matplotlib>=3.8\nnumpy>=1.26\n", StandardCharsets.UTF_8);
        Files.writeString(scripts.resolve("run-python-plots.ps1"),
                powershellRunner(), StandardCharsets.UTF_8);
        Files.writeString(scripts.resolve("run-python-plots.sh"),
                shellRunner(), StandardCharsets.UTF_8);
        System.out.println("  python plotting scripts: scripts/plot_publication_figures.py");
    }

    private static String readme() {
        return """
                # Python publication plotting scripts

                Run from this output directory:

                ```powershell
                python scripts\\plot_publication_figures.py
                ```

                or:

                ```powershell
                .\\scripts\\run-python-plots.ps1
                ```

                The script reads `raw/*.csv` and `experiment_config.json`, then writes
                journal-ready PNG, SVG, and PDF figures to `figures-python/`.

                Required Python packages:

                ```text
                matplotlib
                numpy
                ```

                These plots are intended for manuscript use; the Java figures remain
                available in `figures/` as a dependency-free fallback.
                """;
    }

    private static String powershellRunner() {
        return """
                $ErrorActionPreference = 'Stop'
                $root = Split-Path -Parent $PSScriptRoot
                python (Join-Path $PSScriptRoot 'plot_publication_figures.py') --output $root
                """;
    }

    private static String shellRunner() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
                ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
                python "$SCRIPT_DIR/plot_publication_figures.py" --output "$ROOT_DIR"
                """;
    }

    private static String pythonScript() {
        return """
                #!/usr/bin/env python3
                \"\"\"
                Generate publication-quality manuscript figures for the UBR-CA
                reproducibility suite.

                The script is generated by the Java experiment runner and consumes the
                raw CSV files in an output directory. It writes PNG, SVG, and PDF
                versions of manuscript Figures 2-7 to figures-python/.
                \"\"\"

                from __future__ import annotations

                import argparse
                import csv
                import json
                import math
                import os
                import shutil
                import statistics
                from collections import defaultdict
                from pathlib import Path

                os.environ.setdefault(
                    "MPLCONFIGDIR",
                    str(Path(__file__).resolve().parents[1] / ".matplotlib-cache"),
                )

                try:
                    import matplotlib
                    matplotlib.use("Agg")
                    import matplotlib.patches as patches
                    import matplotlib.pyplot as plt
                    import numpy as np
                except ModuleNotFoundError as exc:
                    raise SystemExit(
                        "Missing Python plotting dependency: "
                        f"{exc.name}. Install dependencies with:\\n"
                        "  python -m pip install -r scripts/requirements.txt\\n"
                        "or, from the experiment output directory:\\n"
                        "  python -m pip install matplotlib numpy"
                    ) from exc


                POLICY_ORDER = ["HEFT", "KRP", "EA-VC", "CCS", "CARS", "UBR-CA"]
                POLICY_COLORS = {
                    "HEFT": "#4C78A8",
                    "KRP": "#72B7B2",
                    "EA-VC": "#54A24B",
                    "CCS": "#ECA82C",
                    "CARS": "#F58518",

                    "UBR-CA": "#E45756",
                    "UBR-CA no migration": "#7F7F7F",
                }
                STRESS_ORDER = ["LIGHT", "MODERATE", "HEAVY"]


                def parse_args() -> argparse.Namespace:
                    parser = argparse.ArgumentParser()
                    parser.add_argument(
                        "--output",
                        type=Path,
                        default=Path(__file__).resolve().parents[1],
                        help="Experiment output directory containing raw/ and experiment_config.json",
                    )
                    return parser.parse_args()


                def configure_matplotlib() -> None:
                    plt.rcParams.update({
                        "figure.dpi": 160,
                        "savefig.dpi": 600,
                        "font.family": "serif",
                        "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
                        "mathtext.fontset": "stix",
                        "font.size": 16,
                        "axes.linewidth": 1.25,
                        "axes.edgecolor": "#222222",
                        "axes.labelsize": 18,
                        "axes.titlesize": 20,
                        "xtick.labelsize": 16,
                        "ytick.labelsize": 16,
                        "legend.fontsize": 16,
                        "grid.color": "#D8DDE3",
                        "grid.linewidth": 0.75,
                        "grid.alpha": 0.8,
                        "lines.linewidth": 2.8,
                        "lines.markersize": 8.0,
                        "patch.linewidth": 0.6,
                        "pdf.fonttype": 42,
                        "ps.fonttype": 42,
                    })


                def read_csv(path: Path) -> list[dict[str, str]]:
                    with path.open(newline="", encoding="utf-8-sig") as handle:
                        return list(csv.DictReader(handle))


                def read_json(path: Path) -> dict:
                    with path.open(encoding="utf-8") as handle:
                        return json.load(handle)


                def f(row: dict[str, str], key: str) -> float:
                    return float(row[key])


                def mean(values: list[float]) -> float:
                    return statistics.fmean(values) if values else float("nan")


                def sd(values: list[float]) -> float:
                    return statistics.stdev(values) if len(values) > 1 else 0.0


                def grouped(rows: list[dict[str, str]], key: str) -> dict[str, list[dict[str, str]]]:
                    result: dict[str, list[dict[str, str]]] = defaultdict(list)
                    for row in rows:
                        result[row[key]].append(row)
                    return dict(result)


                def summary(rows: list[dict[str, str]], metric: str) -> tuple[float, float]:
                    values = [f(row, metric) for row in rows]
                    return mean(values), sd(values)


                def save(fig: plt.Figure, outdir: Path, name: str, tight: bool = True) -> None:
                    outdir.mkdir(parents=True, exist_ok=True)
                    if tight:
                        fig.tight_layout(pad=0.75)
                    for ext in ("png", "svg", "pdf"):
                        fig.savefig(outdir / f"{name}.{ext}", bbox_inches="tight")
                    plt.close(fig)


                def mirror_figure(source_dir: Path, manuscript_dir: Path,
                                  source_name: str, target_name: str) -> None:
                    manuscript_dir.mkdir(parents=True, exist_ok=True)
                    for ext in ("png", "svg", "pdf"):
                        source = source_dir / f"{source_name}.{ext}"
                        if source.exists():
                            shutil.copy2(source, manuscript_dir / f"{target_name}.{ext}")


                def figure_1_framework(outdir: Path) -> None:
                    fig, ax = plt.subplots(figsize=(12.5, 6.2))
                    ax.set_axis_off()
                    ax.set_xlim(0, 1)
                    ax.set_ylim(0, 1)

                    interval = patches.FancyBboxPatch(
                        (0.405, 0.885), 0.19, 0.05,
                        boxstyle="round,pad=0.012,rounding_size=0.012",
                        linewidth=1.2, edgecolor="#7A5C00", facecolor="#FFF1B8")
                    ax.add_patch(interval)
                    ax.text(0.5, 0.910, "Each scheduling interval  $\\\\Delta t$",
                            ha="center", va="center", fontsize=15, fontweight="bold")

                    stages = [
                        ("1", "Bayesian\\nposterior update",
                         ["Collect container", "utilization samples", "Update mean and", "uncertainty"]),
                        ("2", "Ready-task\\nidentification",
                         ["Check DAG", "predecessors", "Build ready-task", "queue"]),
                        ("3", "Robust task\\nplacement",
                         ["Evaluate each VM", "Capacity safety", "Credit feasibility", "Minimum effective cost"]),
                        ("4", "Credit-aware\\nmigration",
                         ["Predict future", "credit balances", "Detect risk", "Migrate at-risk tasks"]),
                    ]
                    xs = [0.045, 0.285, 0.525, 0.765]
                    colors = ["#DCEBFF", "#E7F4DF", "#FFE9D7", "#EFE5FA"]
                    borders = ["#376DAE", "#5A8F42", "#D96A1B", "#7B4EA3"]
                    width, height, y0 = 0.19, 0.54, 0.225
                    for i, ((number, title, bullets), x0, color, border) in enumerate(zip(stages, xs, colors, borders)):
                        box = patches.FancyBboxPatch(
                            (x0, y0), width, height,
                            boxstyle="round,pad=0.012,rounding_size=0.015",
                            linewidth=1.3, edgecolor=border, facecolor=color)
                        ax.add_patch(box)
                        badge = patches.Circle((x0 + 0.022, y0 + height - 0.035),
                                               0.018, facecolor=border, edgecolor=border)
                        ax.add_patch(badge)
                        ax.text(x0 + 0.022, y0 + height - 0.035, number,
                                ha="center", va="center", fontsize=13,
                                color="white", fontweight="bold")
                        ax.text(x0 + width / 2, y0 + height - 0.065, title,
                                ha="center", va="center", fontsize=14.5,
                                fontweight="bold", color="#1B1B1B")
                        for j, bullet in enumerate(bullets):
                            ax.text(x0 + 0.030, y0 + height - 0.165 - j * 0.075,
                                    f"- {bullet}", ha="left", va="center",
                                    fontsize=13.5, color="#1B1B1B")
                        if i < len(xs) - 1:
                            ax.annotate("", xy=(x0 + width + 0.035, y0 + 0.31),
                                        xytext=(x0 + width + 0.010, y0 + 0.31),
                                        arrowprops=dict(arrowstyle="-|>", lw=1.6,
                                                        color="#333333"))

                    component_box = patches.FancyBboxPatch(
                        (0.18, 0.06), 0.58, 0.11,
                        boxstyle="round,pad=0.012,rounding_size=0.015",
                        linewidth=1.1, edgecolor="#8AA9D6", facecolor="#F3F7FE")
                    ax.add_patch(component_box)
                    ax.text(0.47, 0.142, "System components",
                            ha="center", va="center", fontsize=14,
                            fontweight="bold")
                    ax.text(0.47, 0.095,
                            "Workflow manager  |  Monitoring module  |  UBR-CA scheduler  |  Burstable VM pool",
                            ha="center", va="center", fontsize=11.2)
                    ax.annotate("", xy=(0.20, 0.235), xytext=(0.20, 0.17),
                                arrowprops=dict(arrowstyle="-|>", lw=1.3, color="#333333"))
                    ax.annotate("", xy=(0.82, 0.235), xytext=(0.72, 0.17),
                                arrowprops=dict(arrowstyle="-|>", lw=1.3, color="#333333"))

                    save(fig, outdir, "framework", tight=False)


                def figure_2_normalized_cost(root: Path, outdir: Path) -> None:
                    rows = read_csv(root / "raw" / "overall_results.csv")
                    by_policy = grouped(rows, "policy")
                    heft_mean, _ = summary(by_policy["HEFT"], "cost_usd")
                    labels, values, errors = [], [], []
                    for policy in POLICY_ORDER:
                        m, s = summary(by_policy[policy], "cost_usd")
                        labels.append(policy)
                        values.append(m / heft_mean)
                        errors.append(s / heft_mean)

                    x = np.arange(len(labels))
                    fig, ax = plt.subplots(figsize=(8.2, 4.6))
                    colors = [POLICY_COLORS[p] for p in labels]
                    bars = ax.bar(x, values, yerr=errors, color=colors, capsize=3.2,
                                  edgecolor="#333333", linewidth=0.45)
                    ax.axhline(1.0, color="#333333", linestyle="--", linewidth=0.9)
                    ax.set_ylabel("Normalized cost (HEFT = 1.0)")
                    ax.set_xticks(x)
                    ax.set_xticklabels(labels, rotation=25, ha="right")
                    ax.grid(axis="y")
                    ax.set_ylim(0, max(values) * 1.16)
                    for bar, value in zip(bars, values):
                        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,
                                f"{value:.3f}", ha="center", va="bottom", fontsize=15.5)
                    save(fig, outdir, "figure_2_normalized_execution_cost")


                def figure_3_credit_trajectory(root: Path, outdir: Path) -> None:
                    rows = read_csv(root / "raw" / "credit_trajectory_ubr_ca.csv")
                    t = [f(row, "time_hours") for row in rows]
                    minimum = [f(row, "minimum") for row in rows]
                    average = [f(row, "mean") for row in rows]
                    maximum = [f(row, "maximum") for row in rows]

                    fig, ax = plt.subplots(figsize=(8.2, 4.6))
                    ax.plot(t, minimum, label="Minimum", color="#E45756")
                    ax.plot(t, average, label="Mean", color="#4C78A8")
                    ax.plot(t, maximum, label="Maximum", color="#54A24B")
                    ax.fill_between(t, minimum, maximum, color="#4C78A8", alpha=0.10, linewidth=0)
                    ax.set_xlabel("Simulation time (hours)")
                    ax.set_ylabel("CPU credits")
                    ax.grid(True)
                    ax.legend(frameon=False, ncol=3, loc="upper right")
                    save(fig, outdir, "figure_3_credit_trajectory")


                def figure_4_credit_stress(root: Path, outdir: Path) -> None:
                    rows = read_csv(root / "raw" / "stress_results.csv")
                    policies = ["HEFT", "CARS", "UBR-CA no migration", "UBR-CA"]
                    x = np.arange(len(STRESS_ORDER))

                    fig, ax = plt.subplots(figsize=(8.2, 4.6))
                    for policy in policies:
                        y, err = [], []
                        for stress in STRESS_ORDER:
                            subset = [row for row in rows
                                      if row["stress"] == stress and row["policy"] == policy]
                            m, s = summary(subset, "credit_exhaustions")
                            y.append(m)
                            err.append(s)
                        ax.errorbar(x, y, yerr=err, marker="o", capsize=3,
                                    label=policy, color=POLICY_COLORS.get(policy, "#333333"))
                    ax.set_xticks(x)
                    ax.set_xticklabels(["Light", "Moderate", "Heavy"])
                    ax.set_xlabel("Credit-stress regime")
                    ax.set_ylabel("Credit-exhaustion events")
                    ax.grid(axis="y")
                    ax.legend(frameon=False, ncol=2)
                    save(fig, outdir, "figure_4_credit_stress")


                def figure_5_sensitivity(root: Path, outdir: Path) -> None:
                    rows = read_csv(root / "raw" / "sensitivity_summary.csv")
                    panels = [
                        ("interval_seconds", "Scheduling interval $\\\\Delta t$ (s)"),
                        ("lookahead_H", "Lookahead horizon $H$"),
                        ("epsilon", "Risk tolerance $\\\\epsilon$"),
                        ("lateness_lambda", "Lateness penalty $\\\\lambda$"),
                    ]
                    fig, axes = plt.subplots(2, 2, figsize=(12.8, 9.2))
                    axes = axes.ravel()
                    legend_handles = None
                    for ax, (parameter, title) in zip(axes, panels):
                        subset = [row for row in rows if row["parameter"] == parameter]
                        subset.sort(key=lambda row: f(row, "value"))
                        x = [f(row, "value") for row in subset]
                        cost = [f(row, "cost_mean") for row in subset]
                        cost_sd = [f(row, "cost_sd") for row in subset]
                        exhaust = [f(row, "throttled_vm_hours_mean") for row in subset]
                        exhaust_sd = [f(row, "throttled_vm_hours_sd") for row in subset]

                        ax.errorbar(x, cost, yerr=cost_sd, marker="o", capsize=2.5,
                                    color="#4C78A8", label="Cost")
                        ax.set_xlabel(title, fontsize=22, fontweight="bold")
                        ax.set_ylabel("Cost (USD)", color="#4C78A8", fontsize=21)
                        ax.tick_params(axis="both", labelsize=18)
                        ax.tick_params(axis="y", labelcolor="#4C78A8")
                        ax.grid(True)

                        ax2 = ax.twinx()
                        ax2.errorbar(x, exhaust, yerr=exhaust_sd, marker="s", capsize=2.5,
                                     color="#E45756", label="Throttled VM-hours")
                        ax2.set_ylabel("Throttled VM-hours", color="#E45756", fontsize=21)
                        ax2.tick_params(axis="y", labelcolor="#E45756", labelsize=18)
                        if legend_handles is None:
                            legend_handles = (ax.lines[0], ax2.lines[0])

                    if legend_handles:
                        fig.legend(legend_handles, ["Cost", "Throttled VM-hours"], frameon=False, ncol=2,
                                   loc="upper center", bbox_to_anchor=(0.5, 0.995), fontsize=19)
                    fig.subplots_adjust(left=0.09, right=0.91, bottom=0.10, top=0.85,
                                        hspace=0.62, wspace=0.48)
                    save(fig, outdir, "figure_5_sensitivity_panels", tight=False)


                def figure_5_sensitivity_manuscript_panels(root: Path, outdir: Path) -> None:
                    rows = read_csv(root / "raw" / "sensitivity_summary.csv")
                    panels = [
                        ("interval_seconds", "Scheduling interval $\\\\Delta t$ (s)",
                         "figure_5a_sensitivity_interval_seconds"),
                        ("lookahead_H", "Lookahead horizon $H$",
                         "figure_5b_sensitivity_lookahead_H"),
                        ("epsilon", "Risk tolerance $\\\\epsilon$",
                         "figure_5c_sensitivity_epsilon"),
                        ("lateness_lambda", "Lateness penalty $\\\\lambda$",
                         "figure_5d_sensitivity_lateness_lambda"),
                    ]
                    for parameter, xlabel, filename in panels:
                        subset = [row for row in rows if row["parameter"] == parameter]
                        subset.sort(key=lambda row: f(row, "value"))
                        x = [f(row, "value") for row in subset]
                        cost = [f(row, "cost_mean") for row in subset]
                        cost_sd = [f(row, "cost_sd") for row in subset]
                        exhaust = [f(row, "throttled_vm_hours_mean") for row in subset]
                        exhaust_sd = [f(row, "throttled_vm_hours_sd") for row in subset]

                        fig, ax = plt.subplots(figsize=(5.0, 3.75))
                        line1 = ax.errorbar(x, cost, yerr=cost_sd, marker="o", capsize=3.2,
                                            color="#4C78A8", label="Cost")
                        ax.set_xlabel(xlabel)
                        ax.set_ylabel("Cost (USD)", color="#4C78A8")
                        ax.tick_params(axis="y", labelcolor="#4C78A8")
                        ax.grid(True)

                        ax2 = ax.twinx()
                        line2 = ax2.errorbar(x, exhaust, yerr=exhaust_sd, marker="s", capsize=3.2,
                                             color="#E45756", label="Throttled VM-hours")
                        ax2.set_ylabel("Throttled VM-hours", color="#E45756", fontsize=21)
                        ax2.tick_params(axis="y", labelcolor="#E45756", labelsize=18)
                        ax.legend([line1.lines[0], line2.lines[0]], ["Cost", "Throttled VM-hours"],
                                  frameon=False, ncol=2, loc="upper center",
                                  bbox_to_anchor=(0.5, 1.18))
                        fig.subplots_adjust(left=0.18, right=0.84, bottom=0.20, top=0.82)
                        save(fig, outdir, filename, tight=False)


                def inverse_normal_approx(p: float) -> float:
                    # Acklam approximation, matching the Java implementation closely enough for plotting.
                    a = [-39.69683028665376, 220.9460984245205, -275.9285104469687,
                         138.3577518672690, -30.66479806614716, 2.506628277459239]
                    b = [-54.47609879822406, 161.5858368580409, -155.6989798598866,
                         66.80131188771972, -13.28068155288572]
                    c = [-0.007784894002430293, -0.3223964580411365,
                         -2.400758277161838, -2.549732539343734,
                         4.374664141464968, 2.938163982698783]
                    d = [0.007784695709041462, 0.3224671290700398,
                         2.445134137142996, 3.754408661907416]
                    p_low = 0.02425
                    p_high = 1.0 - p_low
                    if p < p_low:
                        q = math.sqrt(-2.0 * math.log(p))
                        return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) / \
                               ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1.0)
                    if p <= p_high:
                        q = p - 0.5
                        r = q * q
                        return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5]) * q / \
                               (((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1.0)
                    q = math.sqrt(-2.0 * math.log(1.0 - p))
                    return -(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) / \
                            ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1.0)


                def figure_6_bayesian_convergence(root: Path, outdir: Path) -> None:
                    config = read_json(root / "experiment_config.json")
                    prior = float(config["prior_variance"])
                    obs = float(config["observation_variance"])
                    epsilon = float(config["epsilon"])
                    z = inverse_normal_approx(1.0 - epsilon)
                    samples = np.arange(1, 101)
                    variance = 1.0 / (1.0 / prior + samples / obs)
                    sigma = np.sqrt(variance)
                    half_width = z * sigma

                    fig, ax = plt.subplots(figsize=(8.2, 4.6))
                    ax.plot(samples, sigma, color="#4C78A8", label="Posterior standard deviation")
                    ax.plot(samples, half_width, color="#E45756", label="95% one-sided half-width")
                    ax.fill_between(samples, 0, half_width, color="#E45756", alpha=0.08, linewidth=0)
                    ax.set_xlabel("Utilization observations")
                    ax.set_ylabel("Posterior uncertainty")
                    ax.grid(True)
                    ax.legend(frameon=False)
                    save(fig, outdir, "figure_6_bayesian_convergence")


                def figure_7_scalability(root: Path, outdir: Path) -> None:
                    rows = read_csv(root / "raw" / "scalability_results.csv")
                    x = [f(row, "tasks") for row in rows]
                    y = [f(row, "scheduler_runtime_mean_seconds") for row in rows]
                    yerr = [f(row, "scheduler_runtime_sd_seconds") for row in rows]

                    fig, ax = plt.subplots(figsize=(8.2, 4.6))
                    ax.errorbar(x, y, yerr=yerr, marker="o", capsize=3.0,
                                color="#4C78A8")
                    ax.set_xscale("log")
                    ax.set_xlabel("Number of tasks (log scale)")
                    ax.set_ylabel("Scheduler CPU time (s)")
                    ax.grid(True, which="both")
                    for xi, yi in zip(x, y):
                        ax.text(xi, yi, f"{yi:.3f}", fontsize=15.5, ha="left", va="bottom")
                    save(fig, outdir, "figure_7_scheduler_scalability")


                def export_manuscript_figures(root: Path, outdir: Path) -> None:
                    manuscript_dir = root / "figures"
                    mappings = [
                        ("framework", "framework"),
                        ("figure_2_normalized_execution_cost", "figure_1_normalized_execution_cost"),
                        ("figure_2_normalized_execution_cost", "figure_2_normalized_execution_cost"),
                        ("figure_3_credit_trajectory", "figure_3_credit_trajectory"),
                        ("figure_4_credit_stress", "figure_4_credit_stress"),
                        ("figure_5a_sensitivity_interval_seconds", "figure_5a_sensitivity_interval_seconds"),
                        ("figure_5b_sensitivity_lookahead_H", "figure_5b_sensitivity_lookahead_H"),
                        ("figure_5c_sensitivity_epsilon", "figure_5c_sensitivity_epsilon"),
                        ("figure_5d_sensitivity_lateness_lambda", "figure_5d_sensitivity_lateness_lambda"),
                        ("figure_5_sensitivity_panels", "figure_5_sensitivity_panels"),
                        ("figure_6_bayesian_convergence", "figure_6_bayesian_convergence"),
                        ("figure_7_scheduler_scalability", "figure_7_scheduler_scalability"),
                    ]
                    for source_name, target_name in mappings:
                        mirror_figure(outdir, manuscript_dir, source_name, target_name)


                def main() -> None:
                    args = parse_args()
                    root = args.output.resolve()
                    outdir = root / "figures-python"
                    configure_matplotlib()
                    figure_1_framework(outdir)
                    figure_2_normalized_cost(root, outdir)
                    figure_3_credit_trajectory(root, outdir)
                    figure_4_credit_stress(root, outdir)
                    figure_5_sensitivity(root, outdir)
                    figure_5_sensitivity_manuscript_panels(root, outdir)
                    figure_6_bayesian_convergence(root, outdir)
                    figure_7_scalability(root, outdir)
                    export_manuscript_figures(root, outdir)
                    print(f"Wrote publication figures to {outdir}")
                    print(f"Wrote LaTeX-ready figure aliases to {root / 'figures'}")


                if __name__ == "__main__":
                    main()
                """;
    }
}
